### ISSUE TITLE
Unable to create Producer with latest 4.0.0. snapshot after parent pom change

### ISSUE THREAD

**Issue by katheris** [vert-x3/vertx-kafka-client#172]
### Version

Latest 4.0.0 snapshot

### Context

My application gets an unhandled exception when called KafkaProducer.create:
```
2020-05-19 19:26:51,640 ERROR [vert.x-eventloop-thread-0] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: io.vertx.core.Context.removeCloseHook(Lio/vertx/core/Closeable;)Z
	at io.vertx.kafka.client.common.impl.CloseHandler.registerCloseHook(CloseHandler.java:48)
	at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.registerCloseHook(KafkaProducerImpl.java:132)
	at io.vertx.kafka.client.producer.KafkaProducer.create(KafkaProducer.java:151)
	at kafka.vertx.demo.PeriodicProducer.setup(PeriodicProducer.java:63)
	at kafka.vertx.demo.PeriodicProducer.lambda$start$0(PeriodicProducer.java:35)
	at io.vertx.core.Future.lambda$onSuccess$0(Future.java:125)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:116)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Promise.handle(Promise.java:52)
	at io.vertx.core.Promise.handle(Promise.java:30)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Promise.handle(Promise.java:52)
	at io.vertx.core.Promise.handle(Promise.java:30)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$getConfig$2(ConfigRetrieverImpl.java:182)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$compute$9(ConfigRetrieverImpl.java:303)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Promise.handle(Promise.java:52)
	at io.vertx.core.impl.CompositeFutureImpl.complete(CompositeFutureImpl.java:209)
	at io.vertx.core.impl.CompositeFutureImpl.succeed(CompositeFutureImpl.java:198)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$0(CompositeFutureImpl.java:39)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.config.impl.ConfigRetrieverImpl.lambda$null$6(ConfigRetrieverImpl.java:273)
	at io.vertx.config.impl.ConfigurationProvider.lambda$null$0(ConfigurationProvider.java:83)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.lambda$schedule$2(EventLoopContext.java:61)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: io.vertx.core.Context.removeCloseHook(Lio/vertx/core/Closeable;)Z
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 48 common frames omitted
```

### Do you have a reproducer?

Project seeing the error:
https://github.com/ibm-messaging/kafka-java-vertx-starter

### Steps to reproduce

1. Clone the above project
2. Run `mvn package`
3. Run `java -jar target/demo-0.0.2-SNAPSHOT-all.jar`
4. See exception

Workaround:
I seem to be able to get around the issue by checking out this repo and  running an mvn install to get it into my local repository.

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by vietj** [comment]
a new snapshot should be deployed, I think it is because removeCloseHook signature changed the return type from boolean to void

**Comment by vietj** [comment]
it should be ok now, can you give a try ? https://travis-ci.org/github/vert-x3/vertx-kafka-client/builds/685847369

**Comment by katheris** [comment]
@vietj it still seems to be happening, even though it looks like maven is pulling the new version:
```
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.1 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/4.0.0-SNAPSHOT/vertx-core-4.0.0-20200520.074501-387.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/4.0.0-SNAPSHOT/vertx-core-4.0.0-20200520.074501-387.pom (28 kB at 137 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-parent/15/vertx-parent-15.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-parent/15/vertx-parent-15.pom (13 kB at 126 kB/s)
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-dependencies/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-dependencies/4.0.0-SNAPSHOT/maven-metadata.xml (605 B at 3.0 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web/4.0.0-SNAPSHOT/maven-metadata.xml (1.9 kB at 9.4 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web/4.0.0-SNAPSHOT/vertx-web-4.0.0-20200518.185803-279.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web/4.0.0-SNAPSHOT/vertx-web-4.0.0-20200518.185803-279.pom (6.3 kB at 21 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-parent/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-parent/4.0.0-SNAPSHOT/maven-metadata.xml (1.0 kB at 5.2 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-parent/4.0.0-SNAPSHOT/vertx-web-parent-4.0.0-20200518.185747-284.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-parent/4.0.0-SNAPSHOT/vertx-web-parent-4.0.0-20200518.185747-284.pom (2.6 kB at 12 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext-parent/35/vertx-ext-parent-35.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext-parent/35/vertx-ext-parent-35.pom (8.5 kB at 230 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext/35/vertx-ext-35.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext/35/vertx-ext-35.pom (1.5 kB at 47 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/maven-metadata.xml
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 5.9 kB/s)
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 2.3 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/vertx-web-common-4.0.0-20200518.185752-282.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/vertx-web-common-4.0.0-20200518.185752-282.pom (497 B at 2.5 kB/s)
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/maven-metadata.xml
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.2 kB/s)
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.2 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/vertx-auth-common-4.0.0-20200519.144210-127.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/vertx-auth-common-4.0.0-20200519.144210-127.pom (1.3 kB at 6.4 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth/4.0.0-SNAPSHOT/maven-metadata.xml
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth/4.0.0-SNAPSHOT/maven-metadata.xml (1.0 kB at 4.4 kB/s)
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth/4.0.0-SNAPSHOT/maven-metadata.xml (1.0 kB at 4.4 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth/4.0.0-SNAPSHOT/vertx-auth-4.0.0-20200519.144158-127.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth/4.0.0-SNAPSHOT/vertx-auth-4.0.0-20200519.144158-127.pom (2.8 kB at 14 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/maven-metadata.xml
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.2 kB/s)
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.2 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/vertx-bridge-common-4.0.0-20191206.153619-35.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/vertx-bridge-common-4.0.0-20191206.153619-35.pom (3.6 kB at 18 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext-parent/34/vertx-ext-parent-34.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext-parent/34/vertx-ext-parent-34.pom (8.5 kB at 243 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext/34/vertx-ext-34.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-ext/34/vertx-ext-34.pom (1.5 kB at 51 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-parent/14/vertx-parent-14.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/vertx/vertx-parent/14/vertx-parent-14.pom (15 kB at 477 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.4 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/4.0.0-SNAPSHOT/vertx-kafka-client-4.0.0-20200519.190943-44.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/4.0.0-SNAPSHOT/vertx-kafka-client-4.0.0-20200519.190943-44.pom (3.7 kB at 19 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config/4.0.0-SNAPSHOT/maven-metadata.xml (1.6 kB at 8.3 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config/4.0.0-SNAPSHOT/vertx-config-4.0.0-20200519.143618-60.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config/4.0.0-SNAPSHOT/vertx-config-4.0.0-20200519.143618-60.pom (1.4 kB at 5.1 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config-parent/4.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config-parent/4.0.0-SNAPSHOT/maven-metadata.xml (1.0 kB at 5.2 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config-parent/4.0.0-SNAPSHOT/vertx-config-parent-4.0.0-20200519.143613-60.pom
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config-parent/4.0.0-SNAPSHOT/vertx-config-parent-4.0.0-20200519.143613-60.pom (4.1 kB at 21 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/4.0.0-SNAPSHOT/vertx-core-4.0.0-20200520.074501-387.jar
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web/4.0.0-SNAPSHOT/vertx-web-4.0.0-20200518.185803-279.jar
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/vertx-web-common-4.0.0-20200518.185752-282.jar
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/vertx-auth-common-4.0.0-20200519.144210-127.jar
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/vertx-bridge-common-4.0.0-20191206.153619-35.jar
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-bridge-common/4.0.0-SNAPSHOT/vertx-bridge-common-4.0.0-20191206.153619-35.jar (11 kB at 21 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/4.0.0-SNAPSHOT/vertx-kafka-client-4.0.0-20200519.190943-44.jar
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web-common/4.0.0-SNAPSHOT/vertx-web-common-4.0.0-20200518.185752-282.jar (23 kB at 32 kB/s)
Downloading from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config/4.0.0-SNAPSHOT/vertx-config-4.0.0-20200519.143618-60.jar
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-web/4.0.0-SNAPSHOT/vertx-web-4.0.0-20200518.185803-279.jar (310 kB at 330 kB/s)
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/4.0.0-SNAPSHOT/vertx-core-4.0.0-20200520.074501-387.jar (1.3 MB at 1.4 MB/s)
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-config/4.0.0-SNAPSHOT/vertx-config-4.0.0-20200519.143618-60.jar (57 kB at 56 kB/s)
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-auth-common/4.0.0-SNAPSHOT/vertx-auth-common-4.0.0-20200519.144210-127.jar (99 kB at 96 kB/s)
Downloaded from snapshots-repo: https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/4.0.0-SNAPSHOT/vertx-kafka-client-4.0.0-20200519.190943-44.jar (126 kB at 114 kB/s)
```

**Comment by katheris** [comment]
I wonder if it's because some of the other vertx dependencies are pulling in other versions:
```
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] netty-buffer-4.1.49.Final.jar, netty-codec-4.1.49.Final.jar, netty-codec-dns-4.1.49.Final.jar, netty-codec-http-4.1.49.Final.jar, netty-codec-http2-4.1.49.Final.jar, netty-codec-socks-4.1.49.Final.jar, netty-common-4.1.49.Final.jar, netty-handler-4.1.49.Final.jar, netty-handler-proxy-4.1.49.Final.jar, netty-resolver-4.1.49.Final.jar, netty-resolver-dns-4.1.49.Final.jar, netty-transport-4.1.49.Final.jar define 1 overlapping resources: 
[WARNING]   - META-INF/io.netty.versions.properties
[WARNING] demo-0.0.2-SNAPSHOT.jar, jackson-core-2.10.2.jar, kafka-clients-2.4.0.jar, logback-classic-1.2.3.jar, logback-core-1.2.3.jar, lz4-java-1.6.0.jar, netty-buffer-4.1.49.Final.jar, netty-codec-4.1.49.Final.jar, netty-codec-dns-4.1.49.Final.jar, netty-codec-http-4.1.49.Final.jar, netty-codec-http2-4.1.49.Final.jar, netty-codec-socks-4.1.49.Final.jar, netty-common-4.1.49.Final.jar, netty-handler-4.1.49.Final.jar, netty-handler-proxy-4.1.49.Final.jar, netty-resolver-4.1.49.Final.jar, netty-resolver-dns-4.1.49.Final.jar, netty-transport-4.1.49.Final.jar, slf4j-api-1.7.21.jar, snappy-java-1.1.7.3.jar, vertx-auth-common-4.0.0-SNAPSHOT.jar, vertx-bridge-common-4.0.0-SNAPSHOT.jar, vertx-config-4.0.0-SNAPSHOT.jar, vertx-core-4.0.0-SNAPSHOT.jar, vertx-kafka-client-4.0.0-SNAPSHOT.jar, vertx-web-4.0.0-SNAPSHOT.jar, vertx-web-common-4.0.0-SNAPSHOT.jar, zstd-jni-1.4.3-1.jar define 1 overlapping resources: 
[WARNING]   - META-INF/MANIFEST.MF
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
```

**Comment by vietj** [comment]
currently working on improving close hooks in master, so yes this is broken

I fixed it, it should be fine now.

**Comment by katheris** [comment]
I've validated it's working now, thanks for sorting it
