### ISSUE TITLE
NPE when using batchHandler

### ISSUE THREAD

**Issue by Strainy** [vert-x3/vertx-kafka-client#279]
### Version

v4.5.9

### Context
I'm running into the following NPE when specifying a `batchHandler` on the consumer. Seems like it's still necessary to specify a no-op `handler()`... even if you just need to use the `batchHandler`?

```
java.lang.NullPointerException: Cannot invoke "io.vertx.core.Handler.handle(Object)" because "handler" is null
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$tracedHandler$11(KafkaReadStreamImpl.java:251)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$run$10(KafkaReadStreamImpl.java:240)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:328)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:164)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:200)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.run(KafkaReadStreamImpl.java:240)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$schedule$8(KafkaReadStreamImpl.java:194)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
	at io.vertx.core.impl.WorkerExecutor.lambda$execute$0(WorkerExecutor.java:68)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
```

### Do you have a reproducer?
You can see the error logged in the tracing tests if you switch the handler to `batchHandler` without _also_ specifying a `handler`, for example:
https://github.com/Strainy/vertx-kafka-client/commit/e1030fac03fc1a38d1ce9ab81d1f704f6c48979c

### Steps to reproduce

Just use `batchHandler` without an individual record `handler`.

### Extra

N/A

**Comment by Strainy** [comment]
Got a fix for the issue here 🙏 
https://github.com/vert-x3/vertx-kafka-client/pull/281

**Comment by tsegismont** [comment]
Fixed by f02269a

**Comment by tsegismont** [comment]
I had to revert the commits in both the main and the `4.x` branches because the build was failing.

@Strainy would you mind creating the PR again ? I hope the test suite can catch the failure

**Comment by Strainy** [comment]
@tsegismont https://github.com/vert-x3/vertx-kafka-client/pull/284 🙏

**Comment by tsegismont** [comment]
Fixed by https://github.com/vert-x3/vertx-kafka-client/pull/286
