### ISSUE TITLE
partitionsFor() requires prior subscribe() or assign()

### ISSUE THREAD

**Issue by tombentley** [vert-x3/vertx-kafka-client#36]
If I call `partitionsFor()` on a `KafkaConsumer`/`KafkaReadStream` without having previously done a `subscribe()` or `assign()` I get a NPE.

java.lang.NullPointerException
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.submitTask(KafkaReadStreamImpl.java:104)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.partitionsFor(KafkaReadStreamImpl.java:472)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.partitionsFor(KafkaReadStreamImpl.java:52)
	at io.vertx.kafka.client.consumer.impl.KafkaConsumerImpl.partitionsFor(KafkaConsumerImpl.java:379)

Workaround: do a `subscribe()` with an empty set of topics before calling `partitionsFor()`.

**Comment by tombentley** [comment]
On reflection I think my PR #37 for this is not correct... by automatically `start()`ing the consumer in a call to `partitionsFor()` is means that subsequently `assign()` and `subscribe()` already have an open connection and therefore don't call `resume()`. Thus the sequence `partitionsFor(), assign()` results in paused consumer, whereas `assign()` would normally result in a non-paused consumer, which is very confusing.

This could be fixed, I suppose, by separating the notion of paused into a 'user-level paused' and a 'internally paused'. This would mean that all the API methods that needed a connection could connect but be implicitly paused except `assign()` and `subscribe()` would unpause and the user level pause would correspond to the `pause()`/`resume()` API. This is quite complicated, but it preserves the existing semantics around `assign()` and `subscribe()`, and no one gets surprised by error calling the other methods before an `assign()` or `subscribe()`.

Alternatively we could document that `partitionsFor()` and other API methods require a prior `subscribe()` or `assign()` (with the empty set if necessary) to open the connection. We would also fix the NPE in the cases where this doesn't happen, but keep the logic around pausing as it currently is.
