### ISSUE TITLE
Issues with vertx-kafka-client and spark!

### ISSUE THREAD

**Issue by gillbates** [vert-x3/vertx-kafka-client#61]
I've attached the demo project organized by gradle to reproduce the issue.
In order to run this demo, we should have Spark setup locally.

The problem is:
When we use vertx and spark together, particularly with vertx-mysql-postgresql-client & vertx-kafka-client in our dependencies, we would have following exceptions when we run Simple.java

Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
at org.apache.spark.SparkConf$DeprecatedConfig.(SparkConf.scala:723)
at org.apache.spark.SparkConf$.(SparkConf.scala:571)
at org.apache.spark.SparkConf$.(SparkConf.scala)
at org.apache.spark.SparkConf.set(SparkConf.scala:92)
at org.apache.spark.SparkConf.set(SparkConf.scala:81)
at org.apache.spark.SparkConf.setAppName(SparkConf.scala:118)
at Simple.main(Simple.java:17)

Caused by: java.lang.ClassNotFoundException: scala.Product$class
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 7 more

but if I comment out following lines in my build.gradle

compile "io.vertx:vertx-mysql-postgresql-client:3.4.2"
compile "io.vertx:vertx-kafka-client:3.4.2"

the Simple.java works as expected ...
[issueproj.zip](https://github.com/vert-x3/vertx-kafka-client/files/1185169/issueproj.zip)

**Comment by gillbates** [comment]
Once we force the scala to be 2.11.8, its working. Thanks for all.

ext {
    scalaVersion = "2.11.8"
}

configurations.all {
    resolutionStrategy {
        force "org.scala-lang:scala-library:${scalaVersion}"
        force "org.scala-lang:scala-compiler:${scalaVersion}"
        force "org.scala-lang:scala-reflect:${scalaVersion}"
    }
}
