### ISSUE TITLE
NullPointerException when committed() called if there are no existing committed offsets present for the consumer group

### ISSUE THREAD

**Issue by tinselspoon** [vert-x3/vertx-kafka-client#81]
When calling `committed()` to retrieve the offsets for a consumer group, a `NullPointerException` may be thrown if the consumer group has not yet committed any offsets for that partition. This can be replicated by creating a consumer with a previously unseen group ID, and doing something like the following.

```java
consumer.partitionsAssignedHandler(partitions -> {
    for (final TopicPartition partition : partitions) {
        consumer.committed(partition, System.out::println);
    }
});
```
This will produce a NPE:
```
ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
	at io.vertx.kafka.client.common.impl.Helper.from(Helper.java:97)
	at io.vertx.kafka.client.consumer.impl.KafkaConsumerImpl.lambda$committed$7(KafkaConsumerImpl.java:370)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$null$1(KafkaReadStreamImpl.java:117)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

The code that is causing the issue appears to be in `KafkaConsumerImpl`:
```java
if (done.succeeded()) {
    handler.handle(Future.succeededFuture(Helper.from(done.result())));
}
```
When `result()` is `null` in the case where no offsets are committed and `Helper.from` assumes the object is non-null.

**Comment by ppatierno** [comment]
Thanks for reporting that, the fix is on its way and ready for being pushed.
